#Created by Oliver Hamburger
#this program calculates the ammount generated by simple and compound interest


#Takes user input of principle ammount, rate, time, and times interest is compounded per year
principle_ammount = float(input("please enter the principle ammount: "))
rate = float(input("please enter the rate as a decimal: "))
time = float(input("please enter the time in years: "))
times_interest_compounded = float(input("please enter the mumber of times interest is compounded per year: "))

#Takes values user inputed and calculates the ammount generated by simple interest
simple = (principle_ammount * rate * time) + principle_ammount




#takes values user inputed and calculates the ammount generated by compound interest
first_part = (rate / times_interest_compounded) + 1
second_part = first_part ** (times_interest_compounded * time)
third_part = principle_ammount * second_part
last_part = third_part + principle_ammount
compound = last_part

#prints the ammount generated by simple interest
print("the ammount generated by simple interest is:" , simple)

#prints the ammount generated by compound interest
print("the ammount generated by compound interest is:" , compound)















